maintainer        "Chamila de Alwis"
maintainer_email  "chamilad@wso2.com"
description       "Apache Stratos Tomcat cartri"
version           "0.1"
# depends           "base"
# depends           "java"
# depends           "agent"